### ISSUE TITLE
[BUG] tissue_type is "Standard Category"

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-explorer#1048]
**Describe the bug**
In Datasets with variable tissue_type, the metadata field is grouping under "Author Categories" despite being [defined in the schema](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.1.0/schema.md#tissue_type).

**To Reproduce**
Look here: https://cellxgene.cziscience.com/e/4023a2bc-6325-47db-bfdf-9639e91042c2.cxg/

**Expected behavior**
tissue_type should group under "Standard Categories" as with other schema-defined fields, if it's not in the Dataset drawer as a uniform value

**Comment by tihuan** [comment]
@niknak33 we have some capacity to do high priority bug fixes, so please help tag the top priority bug fixes with P0 and I'll pull them into Q3 work 🙏 Thanks so much!

**Comment by tihuan** [comment]
Assigned a 3 for now, since we haven't investigated the root cause. Will update points once we get a better idea!

**Comment by jahilton** [comment]
When is this expected to deployed in an environment so that I can QA?

**Comment by rainandbare** [comment]
Should be out next week! I will give you a heads up when it is ready for you to look at. Thank you for your patience!
