### ISSUE TITLE
Bizarre behavior with smoke tests after move to multi dataset paradigm

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-explorer#110]
After migrating the test suit to the multi dataset mode, the commented-out rule below that is
 added via self.app.add_url_rule for the for the leaf endpoint ".../<dataset>" (no trailing "/")
 stopped working; the name of the dataset ("pbmc3k.h5ad") gets spliced out of the subsequent calls for
 static assets, yielding 404 errors:

```
"GET /d/pbmc3k.h5ad HTTP/1.1" 200 -
"GET /d/static/main-6bba7b8203c999fe8040.js HTTP/1.1" 404 -
```

After commenting out this rule, calls to the leaf endpoint are redirected to the branch
 endpoint (".../<dataset>/") and subsequent calls for static assets have the dataset included in the
 route, as desired:

```
"GET /d/pbmc3k.h5ad HTTP/1.1" 308 -
"GET /d/pbmc3k.h5ad/ HTTP/1.1" 200 -
"GET /d/pbmc3k.h5ad/static/main-6bba7b8203c999fe8040.js HTTP/1.1" 200 -
```

This is accomplished by the enabled default `strict_slashes` in Flask's Werkzeug
 routing, which redirects leaf calls to the corresponding branch if present. Read more about this
 at https://werkzeug.palletsprojects.com/en/2.0.x/routing/#rule-format.

It is unclear to me why keeping the leaf endpoint in causes the dataset name, meaning
 the "<dataset>" (or in this case: "pbmc3k.h5ad") portion of the url, to get spliced out. Would be
 good to pinpoint the cause so that we don't run into this issue in the future.

```
self.app.add_url_rule(
    f"/{url_dataroot}/<string:dataset>",
    f"dataset_index_{url_dataroot}",
    lambda dataset, url_dataroot=url_dataroot: dataset_index(url_dataroot, dataset),
    methods=["GET"],
)
```

**Comment by maniarathi** [comment]
@danieljhegeman to update ticket with new title.

**Comment by metakuni** [comment]
@danieljhegeman is this issue still relevant?

**Comment by danieljhegeman** [comment]
I'm not super familiar with the reason for _why_, but I think this rule is in place because otherwise things work locally which _won't_ work when deployed, because we have some redirections or path manipulation that occurs via some piece of AWS that is upstream of the load balancer I think... or possibly just upstream of the web server. I don't remember specifically. But I think it's related to the fact that `https://cellxgene.cziscience.com/e/<dataset_id>.cxg/` works for Explorer but `https://cellxgene.cziscience.com/e/<dataset_id>.cxg` does not (no trailing `/`).

**Comment by danieljhegeman** [comment]
It's not actively causing any problems so long as we don't mind that the trailing `/` is required for Explorer urls.

**Comment by atolopko-czi** [comment]
> It's not actively causing any problems so long as we don't mind that the trailing / is required for Explorer urls.

closing. :)

**Comment by tihuan** [comment]
Ooh yeah I remember this little quirk. Is it easy to just redirect no trailing slash to trailing slash, or could BE handle both cases as the same?
