### ISSUE TITLE
TS typing of continuous/geneExpression/histo-related

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/single-cell-explorer#12]
TS typing fixes added to *categorical* components:
- [ ] client/src/components/continuous
- [ ] client/src/components/brushableHistogram
- [ ] client/src/components/geneExpression
- [ ] client/src/components/miniHistogram
- [ ] client/src/components/rightSidebar

**Comment by tihuan** [comment]
will type these next time we touch the files!
