### ISSUE TITLE
Hide super categories if categories is empty

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-explorer#136]
#### Approach
* Match existing functionality for Author super category.

#### Definition of Done
* Standard super category is hidden if it has no categories.
* Continuous super category is hidden if it is empty.

**Comment by brianraymor** [comment]
I've found a case where this fails. If you watch the video, it looks like batchA and batchB singletons appear and immediately disappear in the Author super-category and then the Author category remains. The singletons show up in the dataset drawer.

https://images.zenhubusercontent.com/397736859/a44b8731-c561-4460-ab73-7014c1ec1b21/screen_recording_2021_11_03_at_5_25_26_pm.mov
