### ISSUE TITLE
TS typing of misc components

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/single-cell-explorer#14]
Add TS typing for:
- [ ] components/autosave
- [ ] components/annoDialog.tsx
- [ ] components/app.tsx
- [ ] components/embedding
- [ ] components/framework
- [ ] components/infoDrawer
- [ ] components/menubar
- [ ] components/labelInput.tsx

**Comment by tihuan** [comment]
Will type next time the files are touched
