### ISSUE TITLE
"Dataset?" - quizzical expression on user's face

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-explorer#148]
When there’s one dataset in a collection and the breadcrumbs are constrained, it looks like there’s an errant “Dataset”. Clicking on it does nothing for example. This may perplex a user.

![Screen Shot 2021-10-14 at 4.36.57 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/8d8f8d04-97e8-495f-8bf0-a74c34729b56)

compared to:

![Screen Shot 2021-10-14 at 4.38.59 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/dc82de75-800e-45fa-8478-7b004df8900e)

@hthomas-czi to review and recommend updates as needed.

**Comment by hthomas-czi** [comment]
@brianraymor After thinking on this, it seems like the best solution is to simply hide the Dataset selector under the conditions you documented: 

1. The collection contains only one dataset
2. The breadcrumbs are width-constrained

**Comment by brianraymor** [comment]
Closing in favor of a more comprehensive review of all emerging feedback collected in [Polishing the seamless experience](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/260).
