### ISSUE TITLE
scrollbars "decorate" the dataset selector in explorer on Linux and Windows

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-explorer#153]
@ambrosejcarr reported that scrollbars _decorate_ the dataset selector on Linux and Chrome. I am able to reproduce on Windows and Edge, but not on macOS and Chrome or macOS and Edge:

![image.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/891b7816-16dd-4243-8159-cda94514f93f)

His configuration - https://www.whatsmybrowser.org/b/4XOV2

**Comment by MillenniumFalconMechanic** [comment]
Note LSB does not display the same scrollbar decorations

![Group](https://user-images.githubusercontent.com/2446424/137551618-84be4987-2466-49e9-9b26-7d8e0c3582c4.png)
.
