### ISSUE TITLE
Fix Seamless collection/dataset dropdown consistency bug

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-explorer#166]
## Need
Seamless dropdown should display the correct datasets after an update or revision

## Approach
- Set Explorer /dataset-metadata API endpoint HTTP cache control headers to no-store, max-age=0 to prevent new caching and clear any existing caches.

## DOD 
[Seamless Collection/Dataset selector contents may not appear or contains outdated datasets#154](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-explorer/154) is fixed
- response time for endpoints is re-benchmarked (as described in [165](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-explorer/165))

**Comment by atolopko-czi** [comment]
Bryan's testing demonstrates continued problems: https://czi-sci.slack.com/archives/C02H1P6D22X/p1635984932008500?thread_ts=1635973674.005400&cid=C02H1P6D22X
