### ISSUE TITLE
Add toast notifying user if a dataset has been revised or deleted

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-explorer#176]
Prior to beginning dev work, check how many revisions have happened in the past month. If there have been more than a couple:

A user should be notified if a dataset has been revised. The genes/genesets/diffexp commands should continue to work against the revised dataset (this works as is now).

A user should be notified if they have an active session on a dataset that has been deleted.

This is follow-up work for the [Caching Redesign](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-explorer/164) epic.

**Comment by atolopko-czi** [comment]
This will no longer be an issue after the Portal Data Mgmt Redesign, since deleted DatasetVersions will still be available.
