### ISSUE TITLE
Remove "single dataset" mode

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-explorer#181]
Before the split of Explorer into separate desktop and hosted repos, the code supported both "single" and "multi-root" dataset modes. Only that latter is needed for hosted explorer. Remove all "single dataset" code, for which there is considerable config-related logic.  (search for "single_dataset").

Worth doing _before_ any config system redesign work, since it may lessen the footprint of the code that needs to be grokked and redesigned.

DoD:
* All configuration logic and default config properties related to "single dataset" mode have been removed
* Explorer works exclusively in "multi-root dataset" mode. All tests pass (unit and E2E).
* RDS postgreql db for Explorer is deprovisioned via single-cell-infra changes.
* Dev documentation updated to remove any mention of "user annotations" or "labels"
* Team informed of change.

**Comment by danieljhegeman** [comment]
Worth noting that removing 'single dataset mode' code does _not_ include removing all/any (I need to go back and look) of the cli code; the cli is used for launching the local development server.

**Comment by metakuni** [comment]
Re: `RDS postgreql db for Explorer is deprovisioned via single-cell-infra changes.` under DoD, see also #1276
