### ISSUE TITLE
Add E2E tests for caching behavior

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-explorer#200]
Add E2E tests on Explorer BE API to assert that:
* Repeated requests of dataset endpoints are cached by CloudFlare (can assert `x-cache: Hit from cloudfront` header exists)
* `/dataset-metadata` endpoint is *not* cached (headers `no-store, max-age=0`)
* [stretch] After replacing a dataset with a new revision _and_ updating collection metadata (e.g. name), the BE API `dataset-metadata/` endpoint returns updated response, reflecting the new S3 URL for the dataset and the updated collection metadata.

One goal of these E2E tests is to ensure that CloudFront configuration is not unwittingly changed in a way that breaks our desired caching behavior.  CloudFront is configured via Terraform, and we have no other real means of "testing" its configuration.

**Comment by Bento007** [comment]
> Repeated requests of dataset endpoints are cached by CloudFlare (can assert x-cache: Hit from cloudfront header exists)

Adding this test will break our ability to run the e2e smoke test locally, since it relies on AWS Cloudfront to add headers.

**Comment by atolopko-czi** [comment]
> > Repeated requests of dataset endpoints are cached by CloudFlare (can assert x-cache: Hit from cloudfront header exists)
> 
> Adding this test will break our ability to run the e2e smoke test locally, since it relies on AWS Cloudfront to add headers.

Possible to conditionally run only in cloud env?
