### ISSUE TITLE
Upgrade Flask package dependency to be > 2.0

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/single-cell-explorer#209]
We previously could not upgrade Flask to the major new release (2.0) because we also had a dependency on Flask-restful which was not compatible with the new major version. Flask-Restful now has a new version, 0.3.9, that is compatible with Flask 2.0 so we should upgrade both. 

Please make sure to also update the requirements in single-cell-infra as well here: `terraform/modules/hosted-cellxgene/common/customize/requirements.txt`.

**Comment by maniarathi** [comment]
This issue needs to be updated to be generalized to update all Python dependencies (including Flask) on the Explorer.

**Comment by atolopko-czi** [comment]
associated PR is merged; both DP & Explorer have Flask >2.0.. Closing
