### ISSUE TITLE
rm GET genesets call

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-explorer#214]
The `GET genesets` API method was used to retriever _user_ genesets, which are no longer supported in hosted Explorer.

- [x] Remove the FE call
- [x] Remove the BE API method implementation

See also https://github.com/chanzuckerberg/single-cell-explorer/pull/180/files/fdc8fc8432b6647ed8a4280acb5e7487862ea50a#r785033752.

**Comment by Bento007** [comment]
Having trouble finding the `Get geneset` call in frontend code.
