### ISSUE TITLE
development stages in the LSB need to be ordered by age and not sorted alphabetically

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-explorer#216]
### Need

**Reference**: [single-cell-data-wrangling](https://czi-sci.slack.com/archives/C024HCSH9PT/p1643136420027600)

@jahilton reported:

> Differing granularity of `development_stage` leads to confusion (In the screenshot below, if I select 'fifth decade human stage', does that include the cells that are '46-year-old human stage'?)

![Screen Shot 2022-01-25 at 10.15.04 AM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/d860d039-d7ff-4b75-8e9f-dbc8ede69c47)

Example datasets - [1](https://cellxgene.cziscience.com/e/e763ed0d-0e5a-4b8e-9514-6da3d9e47956.cxg/) and [2](https://cellxgene.cziscience.com/e/9125f891-45c6-4970-a7fb-312aa9f084a4.cxg/)

### Suggestions

> One thing I think would help would be to append the *_ontology_term_id values to the label values (middle aged human stage [HsapDv:0000092]) so that there is more of a breadcrumb for a user to understand that these might look 'off' because they are ontologized. It also gives them something to follow in order to grab a definition for 'middle aged human stage'

> We also thought of hierarchical drop-downs where 'fifth decade human stage' would include the '46-year-old-human stage' but you could also see that '46yr' is within that group and select/deselect that category if desired

**Comment by brianraymor** [comment]
Due to multiple organisms + multiple development stage ontologies in a [dataset](https://cellxgene.cziscience.com/e/f7a068f1-0fdb-48e8-8029-db870ff11d9e.cxg/), this may require a composite model - see **Developmental stage integration** in the [reference]((https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7778977/)) and this [report](https://github.com/obophenotype/developmental-stage-ontologies/blob/master/external/bgee/report.md).

**Comment by brianraymor** [comment]
Capturing @jahilton's comment from a duplicate issue - [Review recommendations for development_stage values
](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-curation/198
)
I think one issue is that "development stage" is a broad term. But in fact we are trying to capture the most specific "age" that is able to be shared.

A separate issue is that the variation in the ages available & their corresponding labels can result in some ugly lists. Connected to this is the fact that the definition of these labels isn't always clear (eg human middle aged stage).
One possible solution is to append the ontology ID to the label to at least give the user something to chase down (could be done for all schema fields that are submitted as ontology terms).
Another possible solution for this specific field is to shift to displaying the values in terms of start & stop points (as this is how the development ontology terms are truly defined). I played around with seeing how this would look for a few of the more complex datasets.
![Screen Shot 2022-03-09 at 6 02 36 PM](https://user-images.githubusercontent.com/15098808/158288310-900269ba-e00b-4638-8c6a-5eabb833fe14.png)
![Screen Shot 2022-03-09 at 6 03 53 PM](https://user-images.githubusercontent.com/15098808/158288319-a7c73a71-6436-4723-9fec-487c89ff9ecf.png)
![Screen Shot 2022-03-09 at 6 04 37 PM](https://user-images.githubusercontent.com/15098808/158288321-0c061c9a-566e-4e3f-ac21-f014aed4403d.png)

**Comment by signechambers1** [comment]
Closing as a low priority
