### ISSUE TITLE
Analytics: update EXPAND events

### ISSUE THREAD

**Issue by ainfeld** [chanzuckerberg/single-cell-explorer#270]
Events: 
1. `EXPLORER_CATEGORY_EXPAND_BUTTON_CLICKED`
2. `EXPLORER_GENESET_HEADING_EXPAND_BUTTON_CLICKED`
3. `EXPLORER_GENESET_EXPAND_BUTTON_CLICKED`

Update: 
- Event behavior: 
(1) Current: events fire when expanded AND collapsed 
(2) Requested change: events should fire ONLY when expanded

**Comment by tihuan** [comment]
https://github.com/chanzuckerberg/single-cell-data-portal/pull/2547
