### ISSUE TITLE
Add events to hosted explorer to track engagement

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-explorer#275]
We'd like to have metrics that capture whether our users get value from explorer so we can track trends in overall engaged users. For explorer, we are defining this as the number of visitors that take any of the following actions:

- Color a category, standard or author categories
- Run differential expression
- Add a gene and color by that gene
- Add a gene and plot on x/y
- Add a gene + selecting via the histogram

To track this accurately, we need to custom events for the following actions:
- Add a gene and color by that gene
- Add a gene and plot on x/y
- Add a gene + selecting via the histogram

cc @ainfeld

**Comment by atarashansky** [comment]
The actions described already have events  attached to the individual "subactions":

for example:

Adding a gene using the quick search:
`EVENTS.EXPLORER_SUGGEST_MENU_ITEM_CLICKED`

Coloring by a gene:
`EVENTS.EXPLORER_COLORBY_GENE_BUTTON_CLICKED`

Clicking x for the scatterplot: 
`EVENTS.EXPLORER_PLOT_X_BUTTON_CLICKED`

Clicking y for the scatterplot:
`EVENTS.EXPLORER_PLOT_Y_BUTTON_CLICKED`

So "Add a gene and color by that gene" would appear as the `EXPLORER_SUGGEST_MENU_ITEM_CLICKED` event followed by the `EXPLORER_COLORBY_GENE_BUTTON_CLICKED` event.
Do the above sequence of events need to be displayed as a single event?

Also, in "Adding a gene and selecting via histogram"  - could you clarify what you mean by selecting via histogram?

**Comment by signechambers1** [comment]
Yup, plausible makes things a little difficult, we do need those sequence of events to be displayed as a single event and yes, the order matters, they would need to add a gene first.

**Comment by atarashansky** [comment]
Got it. Two more clarifying questions:

### Question 1

So if a user does:
1) Add a gene using quick search
2) Color by a gene
This would show up as something like `ADD_GENE_AND_COLORBY`

But what if a user does:
1) Add a gene using quick search
2) Something else
3) Color by a gene
Should this trigger the `ADD_GENE_AND_COLORBY` event?

### Question 2

> - Add a gene + selecting via the histogram
Do you mean cross-filtering using the brushable histogram?

**Comment by signechambers1** [comment]
Thanks @atarashansky, great questions.

Question 1: Yes, i think the second scenario should also trigger the ADD_GENE_COLORBY event if possible
Question 2: Yes!

**Comment by ainfeld** [comment]
@atarashansky could you add EXPLORER_ prefix to the new events? I'm trying to keep any event specific to one of the tools within the cellxgene suite of tools to include the name of that tool at the beginning of the event name.

**Comment by atarashansky** [comment]
@ainfeld Copy that.

@signechambers1 
Ok, so if there's no timeout (e.g. after > X amount of time, coloring by an added gene will no longer trigger the tracker event), then we could do the following for color by (as an example):

- Check if a gene was produced by quick search
- if YES: change `EXPLORER_COLORBY_GENE_BUTTON_CLICKED` to `EXPLORER_ADD_GENE_AND_COLORBY`
- if NO: keep `EXPLORER_COLORBY_GENE_BUTTON_CLICKED`

For scatter plot, we would add a new event signifying that both X and Y were clicked:
`EXPLORER_SCATTERPLOT_DISPLAYED`

- Check if either of the genes are currently present in the quick search list
- If yes, `EXPLORER_ADD_GENE_AND_SCATTERPLOT_DISPLAYED`
- If no, `EXPLORER_SCATTERPLOT_DISPLAYED`

Does this seem reasonable?

**Comment by ainfeld** [comment]
@signechambers1 Can you color by a gene without first adding a gene?

**Comment by signechambers1** [comment]
@ainfeld you can colorby a gene without adding it if you generate a gene set using differential expression.

@atarashansky those events look reasonable to me but I defer to @ainfeld.

**Comment by atarashansky** [comment]
Great suggestion. I have all the info I need now and will submit a PR soon.

Thanks so much!

**Comment by ainfeld** [comment]
Thanks Alec!!
