### ISSUE TITLE
Vet performance of gene info cards and decide on any performance improvements

### ISSUE THREAD

**Issue by sienacizdziel** [chanzuckerberg/single-cell-explorer#296]
This is a running list of any potential improvements I've brainstormed to the gene info cards feature in explorer that I implemented over my internship this summer. At the moment, none of them are particularly pressing and most are general performance improvements.

**Comment by sienacizdziel** [comment]
Potential performance improvements: 
- Caching (cloudfront? backend?)
- Storing ensembl ID <-> NCBI UID mappings
- **(option 1)** Fetch gene info individually when info button is clicked, but without a search for UID (cuts down API calls by half but still dependent on a successful API call per click)
- **(option 2)** In initial dataset upload, batch fetch info for every gene and save into backend (fastest for end user, but takes up space, adds complexity, won’t adjust for gene info changes in the future, lengthens dataset upload time)

**Comment by sienacizdziel** [comment]
Additional considerations:
- Converting styling from current style consistent with explorer to SDS styling from Figma

**Comment by sienacizdziel** [comment]
Includes testing edge cases of API endpoint
- When an ensembl ID search does not return anything (option: search for gene name, and if that produces more than 1 result, show error message showing that it could not be found in refseq)
- When the API returns empty strings (like no summary)

**Comment by sienacizdziel** [comment]
END OF PROJECT ADDITIONAL IMPROVEMENTS

- [ ] Right now, as a geneset is loaded, the info buttons are disabled to prevent the user from searching a gene info before all genes are loaded. The reason for this is that a gene search is marked as pending (low priority) until all genes are loaded in the geneset, at which point the gene search finally is sent to the backend and then routed to the api endpoint in the data portal. Ideally, a gene search will occur immediately once the button is clicked and will asynchronously load as the genes in the geneset are loading. The current fix has a bug where if you open a geneset, let it load until all buttons are showing, then open another geneset, and while that is loading click an info button from the previous geneset, it will once again wait till the new geneset is entirely loaded before sending the gene info search request.

**Comment by sienacizdziel** [comment]
**Additional performance improvements**

I'd say the speed of gene searches is okay, but if we want to speed this up in the future, there are a few options:
- Local caching on the frontend (there is already caching of the data portal endpoint on CloudFront, so to avoid additional complexity re: invalidations, avoid additional CloudFront caching on explorer)
- Currently each gene search first goes through the gene ID search, then the gene info fetch, and can only be done individually. Use `gene2ensembl` from https://ftp.ncbi.nih.gov/gene/DATA/ (README) to remove the need to search the gene ID before fetching the gene information. Fetches using IDs can be done in batches, so this has the potential to speed up implementation considerably:
  - In initial dataset upload, batch fetch info for every gene and save into backend (fastest for end user, but takes up space, adds complexity, won’t adjust for gene info changes in the future, and lengthens dataset upload time).
  - Fetch gene info individually when info button is clicked, but without a search for UID, instead using the `gene2ensembl` from NCBI (cuts down API calls by half but still dependent on a successful API call per click)

From NCBI: NOTE: As files are added or modified in this ftp site, notification will be sent via the Gene News RSS feed. Maybe should set up an RSS Slack bot for changes in `gene2ensembl`

**Comment by sienacizdziel** [comment]
Note that for future features that might request gene information, the gene_info API endpoint in data portal can be called with either gene name or gene ENSEMBL ID (or both!) and will return gene description, summary, NCBI link, synonyms, and a boolean to say whether or not an exact match occurred (is_ensembl_id_result = TRUE means that it received an exact match result from NCBI)

**Comment by signechambers1** [comment]
Thanks @atolopko-czi , we can close this for now as performance improvements for gene cards on explorer are a low priority.
