### ISSUE TITLE
[BUG] Responses are not compressed - causes major slowdown for large datests

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-explorer#331]
There is no compression happening in production. Response sizes for the 4m cell dataset are upwards of 90mb per categorical. With compression, these should be no more than 5mb. This is likely causing a major slowdown for large datasets.

Before happy deployments, Apache took care of the compression on outgoing responses. It should be possible to configure nginx in the [CZI infra repo](https://github.com/chanzuckerberg/shared-infra) to handle the compression for us: [see here](https://docs.nginx.com/nginx/admin-guide/dynamic-modules/brotli/). This is probably where we would need to configure it: https://github.com/chanzuckerberg/shared-infra/blob/main/terraform/modules/ecs-multi-domain-oauth-proxy/nginx.conf.tmpl.

Alternatively, we could do the compression ourselves in the backend and tack on the content encoding header to the response, but this is hacky and does not scale well.

**Comment by bkmartinjr** [comment]
Adding a bit more investigation.

The responses from cellxgene.cziscience.com *are* compressed, eg, the top-level HTML, JS bundle and CSS.

All REST responds from api.cellxgene.cziscience.com are not compressed.

All of the requests include correct `accept-encoding: gzip, deflate, br`

**Comment by atarashansky** [comment]
These responses are gzip compressed (check `primary_filter_dimensions` and `query`).

https://cellxgene.cziscience.com/scExpression

Something must be different about the deployment process.

**Comment by atarashansky** [comment]
Fixed in #344.

There are two kinds of compression we got working:
1) Gzip compression
2) Brotli compression

 - Gzip compression has slightly improved performance on categories with high cardinality (~1.5x). 
 - Brotli has much better compression on datasets with low cardinality (20-50x, e.g. 2kb vs 90 kb).
 - The tradeoff is that the build complexity for Brotli is higher as nginx needs to be built from source (see Dockerfile in #343), whereas gzip works straight out of the box.
 - Furthermore, the compression speed may be different between the two and this has not been benchmarked.
 - Another consideration is PR #337 - this will change the bulky array-of-strings data type of categoricals with a more optimal integer-coded categorical data structure. Combining PR #337 with #343 (gzip) and #344 (brotli), we see that the difference between the two compression methods on low-cardinality categoricals is only 2x (2kb vs 4kb).
Taking the above into consideration, we decided to go with gzip for now with the knowledge that we can switch to Brotli if it becomes advantageous to do so (e.g. significantly faster compression speeds) - #350.

**Comment by atarashansky** [comment]
Another note - initially, these changes worked on `rdev` but not on `dev`. The reason is due to how Cloudfront was configured in chanzuckerberg/single-cell-infra. We were missing `enable_accept_encoding_brotli` and `enable_accept_encoding_gzip` flags - without them, Cloudfront was nuking the `Accept-Encoding` header from our requests. This is fixed in chanzuckerberg/single-cell-infra#660.
