### ISSUE TITLE
update logo

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-explorer#385]
We need to update the logo and favicon to reflect branding changes

https://drive.google.com/drive/folders/1k3shyEQ3BmInqaKvmT9MdBF85g2MV5dO

**Comment by ashin-czi** [comment]
@seve Is this just for the Explorer, or the Data Portal as well?

**Comment by ashin-czi** [comment]
Is this logo changing as well? I noticed it was just formatted text

<img width="377" alt="image" src="https://user-images.githubusercontent.com/109984998/184194536-7133596b-18d0-41bd-843c-888821f2629d.png">
<img width="117" alt="image" src="https://user-images.githubusercontent.com/109984998/184194820-db84d7ae-0223-4c95-9e88-b5debf1b8201.png">

**Comment by ashin-czi** [comment]
Also put this in the PR but posting here on the ticket itself as well:

Currently the Explorer logo icon is just an HTML SVG element of rectangles, styled to resemble the logo. So it doesn't use any image for the logo currently.

I made updates to have the new icon match the rebranded logo as close that I can, but need a decision to whether keep using the HTML elements, or use the PNG image for the logo.

**Comment by ashin-czi** [comment]
Now ready for staging
