### ISSUE TITLE
Unified nav bar for explorer

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-explorer#411]
This ticket captures the work to add the navigation bar to explorer and related changes.

[Figma design](https://www.figma.com/file/qpE40pnzlVal1U1Oib9EKg/Unified-Navigation?node-id=116%3A46212)

Work includes:
- [x] Adding unified nav bar to explorer
- [x] Removing the question mark icon in the lower right (users can now click on Help and Documentation in nav bar)
- [x] Adding Collections link to bottom of main viz page
- [x] Adding dataset selector to bottom of main viz page
- [x] Update explorer favicon to new icon, should match portal favicon

**Comment by tihuan** [comment]
Duplicate here: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-explorer/383
