### ISSUE TITLE
Access config.dataset_identification when running locally

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-explorer#47]
#### Need
To run locally, the Explorer BE needs to be able to return a complete `config.dataset_identification` for the dataset specified via the command line on launch. For example:

```
{
  ...
  dataset_identification: {
    collection_id: "4e3a3744-24e4-4092-b060-d1d43e5ae1bc"
    collection_visibility: "PUBLIC"
    dataset_id: "8df1a064-c743-43be-a083-9b4d338d3763"
  }
}
```

#### Approach
TBD.

#### Definition of Done
Explorer BE returns a complete `config.dataset_identification` when running locally.

**Comment by MillenniumFalconMechanic** [comment]
Notes from 09/15 meeting with @MDunitz and @NoopDog:

1. Madison to investigate running Explorer FE locally against deployed BE.
2. Mim to follow up with Timmy (possibly with an additional ticket) regarding approach on switching datasets with respect to `globals.API.prefix`.

**Comment by MillenniumFalconMechanic** [comment]
Notes from 09/17 meeting with @MDunitz  and @NoopDog:

1. Update [globals.ts](https://github.com/chanzuckerberg/single-cell-explorer/blob/main/client/src/globals.ts#L134) to point to `https://api.cellxgene.staging.single-cell.czi.technology/cellxgene/d/pbmc3k.cxg/api/`.

2. Remove hacks for switch dataset locally. Datasets will be listed and selectable in the dataset selector but a selected dataset will not be loaded correctly locally.

**Comment by ebezzi** [comment]
No longer needed since we're doing graceful degradation.
