### ISSUE TITLE
Explorer - update FE dependencies

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-explorer#485]
Currently we have three major version upgrades that need further testing to ensure 0 regression. Smoke test is failing for all 3 PRs, so maybe there are runtime errors / API changes we need to investigate further!

https://github.com/chanzuckerberg/single-cell-explorer/pulls

![Screen Shot 2022-10-04 at 3.32.19 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/0c354c16-6df2-4daa-a9d2-55cabbd3bdfa)

The PRs correspond to medium to high severities, so I guess they're not as urgent as critical severity ones!

https://github.com/chanzuckerberg/single-cell-explorer/security/dependabot?q=is%3Aopen+sort%3Aseverity

- [ ] Update and pin FE dependencies
- [ ] Deploy and sanity check that nothing is broken
- [ ] Update [how-to-upgrade-dependencies.md](https://github.com/chanzuckerberg/single-cell/blob/main/how-we-work/how-to-upgrade-dependencies.md)

**Comment by metakuni** [comment]
See also #231
