### ISSUE TITLE
Remove EB code

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-explorer#504]
Remove unused elastic bean stock code. It is no longer used by this repo.

**Comment by danieljhegeman** [comment]
I'm not immediately, off the top of my head, sure of how to properly remove/replace [this](https://github.com/chanzuckerberg/single-cell-explorer/blob/9172e277bf50b63f7b3a8f822e38d6001a287c93/hosted/start.sh#L5)

@Bento007 @atarashansky ?

**Comment by atarashansky** [comment]
`server.eb.app` is used by hosted explorer.
