### ISSUE TITLE
Update version based on commit hash

### ISSUE THREAD

**Issue by blrnw3** [chanzuckerberg/single-cell-explorer#51]
instead of having the version hard coded (and updated when we do a new release) it would be great to have the version based on the current commit hash. Currently if you click the i button on the explorer it displays version but it would be really helpful if it showed the deployed version. 

Version is hardcoded in server/__init__.py

**Comment by metakuni** [comment]
It would be extra nice if we could retrieve the deployed commit hash by hitting an endpoint similar to Portal's `/deployed_version`:
* https://api.cellxgene.cziscience.com/dp/v1/deployed_version

This would make it easier to verify deployments, especially while on-call.

**Comment by atolopko-czi** [comment]
dup of newer issue #582
