### ISSUE TITLE
Bug: Nav bar slow to load on explorer pages

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-explorer#514]
When you click on a dataset to explore from prod, explorer starts to load but the navigation bar doesn't show up right away. Is this possible to fix?

**Comment by metakuni** [comment]
@signechambers1 , is this still an issue? I took a quick look but wasn't able to reproduce.

**Comment by signechambers1** [comment]
No does not look like an issue anymore! Thanks @metakuni . Closing.
