### ISSUE TITLE
Accessing tombstoned datasets in the explorer should redirect to the portal collection page

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-explorer#53]
## Need
- If a user tries to navigate to the explorer page for a tombstoned dataset, the explorer should redirect to the collections page the dataset belonged to

## Approach
- Check if tombstoned is True in the /meta response object
- If it is return a redirect using the collection_id from the response object

## DOD
- explorer page for tombstoned datasets redirects instead of 404ing

**Comment by leslieypark** [comment]
Please note for QAing:
There is a 5 minute delay between a dataset being deleted via the data portal, and the availability of the redirect in the explorer. This is due to how we're caching the dataset metadata in the explorer.
