### ISSUE TITLE
centroid hover state is still available after moving colorby to non-categorical label

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-explorer#530]
If I color-by categorical, turn on labels, then color by continuous. I can still hover over the original categorical values and see the main graph change based on hover state.

**Comment by ashin-czi** [comment]
@seve @signechambers1 Could I get a recording of this issue by any chance?

**Comment by signechambers1** [comment]
@ashin-czi i'm not able to reproduce anymore.

This bug is also now a low priority, let's close and not fix (if im missing the repro instructions).
