### ISSUE TITLE
Add JSON logging

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-explorer#540]
See [Data Portal logging configuration](https://github.com/chanzuckerberg/single-cell-data-portal/blob/3879427ca1358880e1b5bb09eeb1ad9ae3ef364f/backend/api_server/logger.py#L8-L38) for how to introduce JSON logging to the BE of Explorer.

**Comment by atolopko-czi** [comment]
dup of #352?

**Comment by metakuni** [comment]
Since this is a duplicate of 352, shall we close this issue?
