### ISSUE TITLE
Explorer - update BE dependencies

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-explorer#580]
- [ ] Update and pin BE dependencies
- [ ] Deploy and sanity check that nothing is broken
- [ ] Update [how-to-upgrade-dependencies.md](https://github.com/chanzuckerberg/single-cell/blob/main/how-we-work/how-to-upgrade-dependencies.md)

**Comment by metakuni** [comment]
Was not aware that Explorer BE dependencies had been updated already. Could you confirm and if so, close this as done? 🙇

**Comment by atarashansky** [comment]
https://github.com/chanzuckerberg/single-cell-explorer/pull/438
