### ISSUE TITLE
[FEATURE REQUEST] Add correlation ids to logs to improve debugging 

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-explorer#581]
**Is your feature request related to a problem? Please describe.**
Sifting through cloudwatch logs when you discover a problem is slow and tedious. Often you're given a mountain of log records and not enough keywords in the logs to sufficiently filter them. Another added complexity for the API requests is that they are run in parallel, so related logs are not always grouped together. We need a way to identify related logs easily to speed up the debugging process. It also becomes difficult to debug issues that span multiple system components.

**Describe the solution you'd like**
Add a correlation id to each request and return it in the response header. All logs generated during that request must include that correlation id.
Optional: support request chaining to allow requests to contain a correlation_id in the header which can be used to link multiple requests within the logs. For example a request to the data portal could include a correlation_id so the request can be track across explorer and data portal.

## Definition of Done
- Making a request will return `X-Request-Id` as a header and will contain a unique Id that can be used to identify log messages in the backend generated by the request.

**Comment by metakuni** [comment]
Labeling as `data-viz` since this is for Explorer.
