### ISSUE TITLE
Define full set of technical requirements for _colors functionality in explorer

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-explorer#616]
We'd like to determine the requirements for the _colors functionality in explorer for inclusion in schema 4.0. More context [here](https://github.com/chanzuckerberg/single-cell-curation/issues/216).

Please list out the technical requirements so we can pass along to the DP team.

**Comment by brianraymor** [comment]
@signechambers1 @dsadgat - while the schema will define the requirements for curators, my understanding is that data-vis is now responsible for creating a CXG validation module that can be called from `cellxgene-schema` CLI to enforce such requirements. Is there a tracking issue?

**Comment by brianraymor** [comment]
I'd recommend just using:

[do or do not (there is no try) _colors](https://github.com/chanzuckerberg/single-cell-curation/issues/216) to document requirements that you want me to include in schema 4. I'll make the appropriate edits.

[_colors must be validated](https://github.com/chanzuckerberg/single-cell-curation/issues/513) is the placeholder issue for your CXG validation.

**Comment by dsadgat** [comment]
Alec sent to Signe
