### ISSUE TITLE
Collection title at the bottom of Explorer links to a private Dataset

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-explorer#666]
Steps to reproduce:

1. Go to https://cellxgene.cziscience.com/e/9f1a899f-05a0-44c5-8aa9-39df61ae4324.cxg/
2. Click on collections link in the footer
3. You are directed to: https://cellxgene.cziscience.com/collections/a0a4b739-6c98-42f9-b476-094f25cad922/private

Desired result: Link to collections page:
https://cellxgene.cziscience.com/collections/7855daa4-3f34-4aae-b65a-87720c02e7cd

**Comment by jahilton** [comment]
Would love to see this fixed soon. It continues to cause confusion (URL w/ version used in reporting of issue [#693](https://github.com/chanzuckerberg/single-cell-curation/issues/693))

**Comment by signechambers1** [comment]
thanks @jahilton! we have this scheduled for the next sprint.
