### ISSUE TITLE
[BUG] Improper display of genes with non-zero expression in single-cell-explorer quick gene search

### ISSUE THREAD

**Issue by MaximilianLombardo** [chanzuckerberg/single-cell-explorer#679]
**Describe the bug**
A user [identified](https://github.com/chanzuckerberg/cellxgene-census/issues/862) that plotting gene expression via the quick gene search not functional in all of the explorer instances for this collection: [MSK SPECTRUM – Ovarian cancer mutational processes drive site-specific immune evasion](https://cellxgene.cziscience.com/collections/4796c91c-9d8f-4692-be43-347b1727f9d8).

When searching for a gene in the quick gene search, the gene appears and can be added to the UI. If the gene has zero expression, then the gene should not appear in quick gene search. Observed behavior deviates from expected behavior because for a gene that has non-zero expression for any cells ([ex: dendritic cells](https://cellxgene.cziscience.com/e/97d9238c-1a39-4873-b0bb-963ec2d788e6.cxg/)), the expected histogram of gene expression values (distribution of expression values across all cells in the dataset) should appear. The observed behavior is pictured below

<img width="365" alt="image" src="https://github.com/chanzuckerberg/single-cell-explorer/assets/25663501/661dc161-a18a-4a89-ad4a-dfda32a9fdbc">

A cursory check of other collections in the data portal seem to indicate that this is the only collection affected.

**To Reproduce**
1. open [MSK Spectrum Collection](https://cellxgene.cziscience.com/collections/4796c91c-9d8f-4692-be43-347b1727f9d8)
2. Open the dendritic cells explorer instance
3. Plot a gene (I've tried MALAT1, ATM, ACTB which all generate the unintended behavior)
4. Observe that instead of histogram, you get an ":0"

**Expected behavior**
Described in detail above - histogram showing the distribution of expression values in cells where the gene was detected.

**Screenshots**
Error screenshots above. I also downloaded the object to manually confirm that there were non-zero expression values in `adata.X` for an example gene ['MALAT1'] that manifests the error in the hosted explorer instance. See screenshot below:

![image](https://github.com/chanzuckerberg/single-cell-explorer/assets/25663501/ef52de57-006c-4481-b7a4-c16118756a67)

**Version (please complete the following information):**
 - Browser [chrome]:
 - Version [Version 119.0.6045.159 (Official Build) (x86_64)]
 - MacOS Sonoma 14.1.1

**Additional context**
There may be an additional dataset formatting issue (separate issue filed [here](https://github.com/chanzuckerberg/single-cell-curation/issues/693)) that may help with debugging, but the deviant behavior does not seem to be due aberrant data formatting alone

**Comment by jahilton** [comment]
I believe there's some bug in the above code/plot provided because MALAT1 has no non-zero values in X. The "Figure 1" shows the raw.X plot, for which MALAT1 has many non-zero values.

However, in this case, MALAT1 is all 0s in X because it was filtered out. The revision we are submitting is correctly annotating that feature (and many others) as feature_is_filtered:True.
Explorer should have some awareness of filtered genes and communicate that to the user (ideally, it will also communicate that there is raw data for that feature so they don't assume it's fully absent)

**Comment by MaximilianLombardo** [comment]
Hi all, updating this thread because another user has reported a similar issue in another collection ([Cheng et. al., 2018](https://cellxgene.cziscience.com/collections/43d4bb39-21af-4d05-b973-4c1fed7b916c)).

context:

> Hi, I am trying to explore the Cheng et. al. (2018) Cell Reports study entitled, “Transcriptional programming of normal and inflamed human epidermis at single-cell resolution”. Unfortunately, when I query genes through the Explorer, every gene has 0 counts. The landing page works, and I can see the UMAP, but there is some issue linking cells to corresponding gene expression counts.

@jahilton not sure if there is also a data issue worth following up on in here as well.

**Comment by jahilton** [comment]
@MaximilianLombardo There is no data issue. It is this...
>Explorer should have some awareness of filtered genes and communicate that to the user (ideally, it will also communicate that there is raw data for that feature so they don't assume it's fully absent)
