### ISSUE TITLE
Install and setup Playwright

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-explorer#693]
- [ ] Install Playwright dependencies.
- [ ] Update project configurations to include Playwright.
- [ ] Make necessary adjustments to package.json.
----
https://github.com/chanzuckerberg/single-cell-data-portal/pull/589

Migrate Jest to Playwright Test Runner: https://github.com/chanzuckerberg/single-cell-data-portal/pull/3405

**Comment by tihuan** [comment]
I'm assuming we'll use Playwright Test Runner instead of Jest test runner too? If so, should we include the PR from DP where we switched to Playwright Test Runner here too? @seve
