### ISSUE TITLE
Configure Playwright

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-explorer#694]
- [ ] Update any custom Jest configurations to work with Playwright.
- [ ] Update any setup or pre-test files to use Playwright.
---
https://github.com/chanzuckerberg/single-cell-data-portal/pull/589

Use Playwright project dependencies to set up pre-test files!

https://github.com/chanzuckerberg/single-cell-data-portal/pull/5104

**Comment by tihuan** [comment]
@seve I added this PR in the description to showcase how to set up pretest files before running tests:

https://github.com/chanzuckerberg/single-cell-data-portal/pull/5104
