### ISSUE TITLE
No tests are being run against deployments post promotion

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-explorer#711]
NOTES:
1. We might see failing tests, so bump it up to 3 points

**Comment by tihuan** [comment]
@dsadgat also setting a P0 on this before the spacial work starts, so we have more confidence in deployment, especially since Explorer doesn't have PR rdevs 😭

**Comment by tihuan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-explorer/711?planning-poker) with Zenhub @kaloster @seve
