### ISSUE TITLE
test: fix tests failing on GHA

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-explorer#715]
The following are only failing on GHA, most likely due to a race condition with undo/redo

- "create a new geneset and undo/redo"
- "edit geneset name and undo/redo"
- "delete a geneset and undo/redo"
- "delete gene from geneset and undo/redo"

**Comment by tihuan** [comment]
Now that we have GHA test artifacts, we can use Playwright Tracer to investigate why the tests are only failing in GHA 🎉 !

@seve can you please take this ticket please? 🙏 

Thank you!

**Comment by tihuan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-explorer/715?planning-poker) with Zenhub @kaloster @seve
