### ISSUE TITLE
Prepare 4.2 schema datasets for feature development and testing

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-explorer#724]
Context:
In order for the eng team to test and develop the spatial feature, we'll need 1 to 3 datasets on schema 4.2

DoD:
1. Work with Nik and DP team on adding spatial data related 4.2 schema to 1 to 3 datasets from DP 
2. **Replace** the development dataset `pbmc3k.cxg` to have one with schema 4.2 conforming spatial data - we'll a dataset provided by Jenny and convert it to `.cxg`
2. Engineers can spin up local Explorer development env with a dataset that has 4.2 schema spatial data
3. All tests pass with updated hard coded assertion values

**Comment by kaloster** [comment]
moving this back to disorder and will resume once 4.2 is finalized

**Comment by kaloster** [comment]
https://czi-sci.slack.com/archives/C02TSE92DBM/p1706908735169079?thread_ts=1706897830.289949&cid=C02TSE92DBM

from @jychien:
----
I’ve mocked up an visium h5ad (demo_visium.h5ad):
Uploaded it to [google drive](https://drive.google.com/file/d/1_8lY7-xDjILlAFnUb-Qw3kDNnYOPxEE7/view?usp=sharing). The corresponding dataset found in:
[CxG](https://cellxgene.cziscience.com/e/dc5f82de-5919-4056-a2c8-c26d538d4418.cxg/)
contributor hosted (with image)
I’ve matched it to the best of my understanding, pending BrianR’s final draft of the schema. The fields (obsm, images, and scalefactors) relevant to viz team should be stable, though.
I have not included any in_tissue=0 spots (as these would not pass validation)
I unfortunately had to mock up the serial number and placed in adata.uns[‘spatial’][library][‘metadata’][‘slide_serial_number’].
I’ve renamed ‘X_spatial’ to ‘X_spatial_orig’ and left it in there to meet current requirement that there needs to be at least one embedding with key ‘X_’

**Comment by tihuan** [comment]
Thanks so much for adding the update here, @kaloster 🙏 🎉 !

**Comment by tihuan** [comment]
Updated points to 5, because we need to convert a schema 4.2 h5ad file provided by Jenny to somehow work with the cxg conversion script, which the validation step only works with the existing schema. So some trial and error will be needed to get this done

Maybe DP Team can help!

CC: @seve @Bento007 anyone else? Thank you!

**Comment by seve** [comment]
Here's the dp code for conversion: https://github.com/chanzuckerberg/single-cell-data-portal/blob/29e2ca38f422d3e60a6518cae5be2c45cbc9ce2e/backend/layers/processing/process_cxg.py#L4

**Comment by tihuan** [comment]
Maybe @kaloster can run the conversions script Jenny's dataset and see if we get any errors first!

**Comment by niknak33** [comment]
Will be worked on after User Story 1 (currently worked on by Ronen)

**Comment by tihuan** [comment]
@tihuan add blocker by cxg script

**Comment by tihuan** [comment]
Blocker #6659 added

**Comment by tihuan** [comment]
We now have super-cool-spatial.cxg!
