### ISSUE TITLE
Revisit image rendering code, since the image seems flipped

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-explorer#729]
Context:
1. In Loupe Browser, the same image is rendered differently than in Explorer, so I wonder if we need to double check if we're somehow rendering the image incorrectly

DoD:
1. The image should be displayed the same orientation as in Loupe Browser?<img width="1229" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWdSQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--813ce83a2e0c8ce6a0b3d5dc6556b151486ec465/Screenshot%202024-01-30%20at%2011.31.29%E2%80%AFAM.png" alt="Screenshot 2024-01-30 at 11.31.29 AM.png" />

NOTES:
1. Timmy: Seve raised a good point that we should cross check to see if other embedding modes are rendered correctly too

**Comment by seve** [comment]
So this finding means that all of our embeddings are being rendered upside down. Does this mean we should fix all embeddings or should we only implement this for spatial?

**Comment by seve** [comment]
The above is an incorrect assumption

**Comment by tihuan** [comment]
Oh that's a really great question though! 

I guess if there's a way we could compare how other people render the same umap, we'd hopefully be able to tell if ours is rendered differently lol?

Probably also depends on where in the code we need to tweak to get the spatial mode to render correctly, if it's scoped to just the spatial code path (say, how we read the GRB matrix), then hopefully it means other embedding modes are working just fine, and comparing how other people render the same umap will give us better perspective too

**Comment by tihuan** [comment]
I just added a note in the ticket description to capture the question you raised, Seve! Thanks for flagging this 🎉 !

**Comment by tihuan** [comment]
Push out of MVP, because it likely won't affect UX

CC: @niknak33

**Comment by tihuan** [comment]
We will fix this by flipping the image at cxg conversion time per #839
