### ISSUE TITLE
Add feature flag

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-explorer#741]
Context:
1. In order to test out the feature in dev/staging/prod, we need a feature flag to hide the spatial mode 

DoD:
1. Implement a simple feature flag mechanism similar to DP
2. Decide a flag name for the spatial mode. Maybe just `spatial=true`?
3. Hide the image button in the toolbar that shows the image layer
4. Timmy: WIP (see discussion in comments above) - show one spatial option when feature flag is off and 2 spatial (full res and high res) options when on

NOTES:
1. Timmy: There are also fields we might need to hide in the left sidebar, but the decision is pending. CC: @niknak33 
2. Timmy: 2/6/2024 - As noted below by Brian, the low res spatial option is removed from the schema

**Comment by tihuan** [comment]
@niknak33 thinking about whether to show the spatial mode in the embedding option, I just remembered that the new spatial mode supposedly will update the embedding option to have 3 spatial modes (spatial-full-res, spatial-hi-res-, and spatial-low-res) instead of the current 1 "spatial" option.

So I suppose the feature flag will need to make sure we show 1 spatial option when the feature flag is off, and 3 options when it's on?

Thank you!

CC: @seve

**Comment by brianraymor** [comment]
Low resolution was cut from the [visium draft](https://github.com/chanzuckerberg/single-cell-curation/issues/674#issue-1954961345) which should be the source of truth. I'm updating the draft in real-time as a final review is completed this week. I recommend also following the conversations on #cell-science-modalities.

**Comment by tihuan** [comment]
Thanks so much for the headsup, Brian 🙏 !! Will remove low-res from the requirement and keep an eye on the channel 💡 !

**Comment by seve** [comment]
@tihuan I think the ticket captures the work needed for a FE fork, but do you predict we'll need any forking on the backend side of things?

**Comment by tihuan** [comment]
Oh that's a really good point! I assumed that there's no breaking changes in the BE, so FE could control what endpoints to call. But @kaloster please help here thank you!
