### ISSUE TITLE
Analytics (update): Spatial Mode MVP Launch Walkthrough

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-explorer#745]
### Overview
**Tool**: Explorer
- Feature (Optional): Spatial Mode

**Description**: Need to make sure Spatial Mode MVP has relevant analytics in place for beta launch in public

### Updates needed
`<Event name>`
- Current: `<Description of how the event works currently>`
- Requested change: `<Description of the update needed>`

#### People to cc
**PM**: @niknak33 
**DS**: @ainfeld 

Privacy policy: https://cellxgene.cziscience.com/privacy

**Comment by tihuan** [comment]
@ainfeld ticket created!

**Comment by ainfeld** [comment]
thank you so much @tihuan!!

**Comment by tihuan** [comment]
@atolopko-czi this is the analytics ticket linked in the tech spec thank you!

**Comment by tihuan** [comment]
closing this one in favor for https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6667 thank you! #6667
