### ISSUE TITLE
Catch All e2e Tests

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-explorer#799]
Context:
In case we missed any cases in the User Story tickets, this ticket will implement them

DoD:
1. Ensure we have e2e tests in place for all User Stories - missing Story 4
2. ~Ensure existing e2e tests have umap plots in Chromatic snapshots~
3. ~Intermitted snapshotting~
4. ~Run existing e2e tests against spatial dataset~

**Comment by tihuan** [comment]
Timmy is working on running spatial dataset on the existing e2e tests

**Comment by tihuan** [comment]
I closed User Story 1, 2, and 3 since the e2e tests are all covered in https://github.com/chanzuckerberg/single-cell-explorer/pull/854

**Comment by tihuan** [comment]
I'll now work on adding Intermitted snapshots to all Chromatic tests

**Comment by seve** [comment]
#871
