### ISSUE TITLE
tech: add smoke tests for cellguide cxg features

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-explorer#811]
CellGuide CXG tests to be written:
 - Assert no author categories or standard categories - done
 - Marker Gene Sets is visible and collapsed. Expansion reveals expected gene sets - done
 - Gene sets are alphabetically sorted. - done
 - Gene set expansion works as expected. - done
 - Gene set modification/deletion and page refresh resets the gene set - done
 - Categorical labels are sorted in descending order by mean expression when genesets are colored by. - done
 - Labels with 0 cells after subsetting are filtered out. - done

**Comment by tihuan** [comment]
just checking in: Is this being worked on this week 👌 ? Thank you!

**Comment by atarashansky** [comment]
I'll add this to next sprint, @tihuan ! I won't be able to get to it this one.

**Comment by tihuan** [comment]
All good! Thanks so much, Alec!
