### ISSUE TITLE
Remove QC Metrics from Embedding Options

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-explorer#824]
Context:
Currently in the embedding dropdown we show irrelevant QC options

DoD:
Only show relevant embedding options<img width="822" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL25mQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94c5e1cd027efb0a1a1090cd4572e8f6689c8c37/image.png" alt="image.png" />

Thanks for the reminder, @sidneymbell !!

**Comment by tihuan** [comment]
We're figuring out in Slack to find a way to identify embedding options:

https://chanzuckerbergteam.slack.com/archives/C06FM5ZQE3Y/p1710430818270119?thread_ts=1710355133.485869&cid=C06FM5ZQE3Y

**Comment by tihuan** [comment]
Bumped this down to P1, since QC embedding options seem to exist on prod already

**Comment by kaloster** [comment]
As discussed in slack, the conversion scrip already identifies valid embeddings as those with `X_` prefix in the AnnData

https://github.com/chanzuckerberg/single-cell-data-portal/blob/be8e76229ce06c7d42988214af192b144d199177/backend/layers/processing/h5ad_data_file.py#L116

I think we can safely close out this one and revisit should this arise again - as far as I can tell this was triggered by a specific dataset and possible that it was a specific dataset issue. I haven't seen those in other datasets.

**Comment by kaloster** [comment]
cc: @tihuan

**Comment by tihuan** [comment]
Yeah that's my impression too! @sidneymbell is it okay to close this ticket? Thank you!

**Comment by kaloster** [comment]
Closing this ticket as per @sidneymbell
