### ISSUE TITLE
[2Q2024] Revise convert to cxg pipeline for deep zoom tiles [Previously: Learn CryoET Deep Zoom Data Pipeline Code]

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-explorer#839]
RK:  Revise `cxg` conversion script and add logic for `uns` data  conversion - 
- NEW(Timmy): We also need to crop the image to use the short side of width/height, so the image is a square. This way we have 1:1 ratio, which simplifies the rendering
- NEW(Timmy): We also need to flip the image before we generate the deep zoom tiles (Timmy has code in ticket comment)
- On each iteration - along with copying `uns` data to the `cxg`, add logic to generate deep zoom tiles and xml manifest (using vips) for openseadragon deep zoom, based on the spatial metadata stored in AnnData
- Save tiles and manifest to an S3 bucket under directory `spatial-deep-zoom` ([Slack context](https://chanzuckerbergteam.slack.com/archives/C06FM5ZQE3Y/p1713816697456979))
- Figure out how deep zoom files will be copied across dev/staging/prod
- Add unit tests for above

DoD:
- When above is complete, working and tested - and s3 bucket is populated with tiles and manifest in the desired hierarchy per dataset
- Make sure above is compatible with MVP and Deep zoom implementation

Reference: https://github.com/chanzuckerberg/single-cell-explorer/pull/879

**Comment by tihuan** [comment]
Timebox to 5, since it involves possible coordination with Jess and Manasa on Imagining Team

**Comment by kaloster** [comment]
Previous description **************************
Context:
1. https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/main/ingestion_tools/scripts/mrc2omezarr.py
2. Jess and Manasa implemented the pipeline above, so we should reach out for consultation as needed

DoD:
1. Investigate CryoET pipeline and see how translatable it is to Cell Science's existing pipeline

**Comment by kaloster** [comment]
Description revised to _as well as_ for adding logic instead of replacing

**Comment by tihuan** [comment]
@kaloster 

Code to crop and flip the image before generating deep zoom files 👌

```py
def spatial_metadata_get(spatial):  # type: ignore
    """
    Returns an object containing spatial metadata, including image width and image height.
    """
    resolution = SPATIAL_IMAGE_DEFAULT_RES

    try:
        library_id = list(spatial.keys())[0]
        image_array = spatial[library_id]["images"][resolution]
    except KeyError as e:
        raise Exception(f"spatial information does not contain requested resolution '{resolution}'") from e

    # Convert the image to a uint8 numpy array scaled to 0-255
    image_array_uint8 = np.uint8(image_array * 255)

    # Convert the numpy array to a PIL Image
    image_pil = Image.fromarray(image_array_uint8)

    # Crop the image using a predefined crop_box function
    image_pil = image_pil.crop(crop_box(image_pil.size))

    # Save the cropped PIL image to a BytesIO stream in WEBP format
    response_image = io.BytesIO()
    image_pil.save(response_image, format="WEBP", quality=90)
    image_str = base64.b64encode(response_image.getvalue()).decode()

    # Preparing data for pyvips from the cropped numpy array

    # NOTE: Flip the image vertically, since somehow the client flips the image
    image_pil = image_pil.transpose(Image.FLIP_TOP_BOTTOM)

    # Convert the flipped PIL Image back to a numpy array
    flipped_array_uint8 = np.array(image_pil)

    h, w, bands = flipped_array_uint8.shape
    linear = flipped_array_uint8.reshape(w * h * bands)
    vipsImage = pyvips.Image.new_from_memory(linear.data, w, h, bands, "uchar")

    # Save as Deep Zoom Image (this will create a directory with tiles and a .dzi file)
    vipsImage.dzsave("./server/common/web/static/deep_zoom/spatial", suffix=".jpeg")

    h = w = min(h, w)  # Adjust for 1:1 aspect ratio

    spatial_metadata = {
        "spatial": {
            "imageWidth": w,
            "imageHeight": h,
            "libraryId": library_id,
            "image": image_str,
        }
    }

    return spatial_metadata
```

**Comment by tihuan** [comment]
Related ticket: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-explorer/913

**Comment by tihuan** [comment]
Related ticket to flip the image:

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-explorer/898
