### ISSUE TITLE
[2Q2024] Add 2 endpoints to serve openseadragon with manifest and tiles [Previous: Create Tiled Images for OpenSeadragon to consume]

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-explorer#840]
RK:  generate the following endpoints

1. Add an endpoint to serve openseadragon manifest (dzi) for deepzooming from an s3 bucket
2. Add an endpoint to serve openseadragon tiles/image paths for deepzooming from an s3 bucket
3. Check if it makes sense to combine both into a single endpoint
4. Add unit tests

DoD:
Above works as expected and tested

Reference: https://github.com/chanzuckerberg/single-cell-explorer/pull/879

**Comment by tihuan** [comment]
Timebox to 5

**Comment by tihuan** [comment]
Thanks for updating the ticket, Ronen!

**Comment by kaloster** [comment]
After further discussion with @tihuan it was greed that this may not be necessary since both tiled images files and XML manifest will be served as static assets from CloudFront cache

**Comment by tihuan** [comment]
Yeah and likely FE can just use a dictionary to figure out which CloudFront to hit, depending on the environment the Explorer is running in

We'll still leave this open for now until we're 100% sure we don't need this ticket anymore lol

**Comment by tihuan** [comment]
Put back to disorder, since we likely don't need this ticket anymore

**Comment by kaloster** [comment]
Closing this out
