### ISSUE TITLE
Export Image: Add color by legends for continuous metadata

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-explorer#853]
The graph downloads currently don't have any legends, if the colorby value is a piece of continuous metadata we should include the legend in the downloaded image.

Related ticket: #393

**Comment by tihuan** [comment]
@seve this feels like a 1 point, but please update if I'm missing something. Thank you!

**Comment by tihuan** [comment]
@seve gentle ping thank you!
