### ISSUE TITLE
BUG: Selected cells discrepancy between umap and spatial

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-explorer#858]
Context:
Slack: https://czi-sci.slack.com/archives/C0247APK621/p1711647089759669

Couple things to iron out towards Visium support. They may be caused by an embedding having null values for some of the obs.
~1. `umap` shows `4992 of 4992 cells`, but only 4113 cells are included in the `obsm[‘X_umap’]`~. - Split out its own ticket #936 ([zenhub](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-explorer/936))
1. The `spatial` embedding will show `4113 of 4992` cells, but all 4992 cells are included in `obsm[‘X_spatial’]`.
1. The spatial embedding shows some dots as very small

Toggling triggers/resolves

Repro: start on umap (bug1) --> spatial --> umap --> spatial (bug2 + bug3)

Example: https://cellxgene.cziscience.com/e/a3b219d6-6606-4d82-82fe-fe76f3889c3c.cxg/

Bug 1:

Current:  umap shows 4992 of 4992
Fix: Should show 4113 of 4113
<img width="1622" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1FkQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc40b833d530610607d75a329b49316ddb8c88dc/Screenshot%202024-03-28%20at%2011.34.22%E2%80%AFAM.png" alt="Screenshot 2024-03-28 at 11.34.22 AM.png" />

Bug 2:
Current: Show 4113 of 4992 selected in spatial mode
Fix: Should show 4992 of 4992 selected in spatial mode

Bug 3:
Current: 879 (4992 - 4113) dots are small due to them being unselected
Fix: All dots should be the same size

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzhkQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94ebac97112b0933bab33a118aee0b69c171f5b4/Screen%20Recording%202024-03-28%20at%2010.19.33%E2%80%AFAM.mov)

**Comment by tihuan** [comment]
@seve please help point this ticket thank you!

**Comment by tihuan** [comment]
@seve gentle ping thank you!

**Comment by seve** [comment]
Was looking around this area of the codebase, and I'm worried this might be a bug/issue with the annomatrix code. Particularly the embedding subset view creation.

**Comment by tihuan** [comment]
Thanks for the update, Seve! Do you have enough information to point this ticket or do you need some time dig more? Thank you!

**Comment by tihuan** [comment]
Ah sorry just saw that you pointed a 2 a month ago lol Is it still a 2?

**Comment by tihuan** [comment]
bumped to 3 for safety

**Comment by tihuan** [comment]
This is now timeboxed to a 2 as a spike!

**Comment by tihuan** [comment]
I'll work on this one once I send out a PR for #936 tomorrow

**Comment by tihuan** [comment]
figuring out how to reproduce this locally
