### ISSUE TITLE
Update `cxg` conversion script to eliminate hires data post deep zooming

### ISSUE THREAD

**Issue by kaloster** [chanzuckerberg/single-cell-explorer#885]
Post deep zooming feature, there'a no need to keep high res data inside `cxg` datasets. 

Remove it from the `cxg` conversion script mapping for `uns/spatial` in order to trim out unnecessary data.

DoD:
- Remove mapping entry from conversion script.
- Manually trigger pipeline against the revised script

**Comment by tihuan** [comment]
@kaloster I'm thinking a 1 pointer, but please update if not the case thank you!
