### ISSUE TITLE
Implement analytics

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-explorer#901]
Context:
1. This is the placeholder to remind ourselves to implement all necessary analytics for beta launch!

**Comment by tihuan** [comment]
@ainfeld IIRC you have analytics tickets created already 😄? If so, I'd love to link them here or just close this ticket lol Thank you!

CC: @niknak33

**Comment by ainfeld** [comment]
@niknak33 did you already create an analytics ticket for spatial updates?

**Comment by niknak33** [comment]
@tihuan - Amanda and I synced, do you have a preference on how you want to see the tickets. We had analytics based per user story like - https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6667 or do you want all analytics in 1 big ticket?

**Comment by tihuan** [comment]
Hurray! Thanks so much, Nik! I think separate tickets sounds good 🙏 

But can you please help adding the tickets in the ticket description as a list, and then I'll convert this ticket into an analytics epic to track completion 😁

Thanks again!

**Comment by tihuan** [comment]
Closing this in favor of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-explorer/909!
