### ISSUE TITLE
Deep Zoom Assets on S3 via Argus

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-explorer#913]
Context:
1. Since Explorer is migrating to use Argus, we need to make sure Deep Zoom assets will still be on S3 and accessible via `/spatial-deep-zoom/*` path

DoD:
1. Deep Zoom assets will still be on S3 and accessible via `/spatial-deep-zoom/*` path

NOTES:
1. Please work with Jake on this thank you!

**Comment by tihuan** [comment]
@ebezzi actually I think you know this better than Ronen, so can we ask for your help to sync with Jake on porting this over to Argus? Thank you!

**Comment by ebezzi** [comment]
Don't think this will be a problem - assets are served through Cloudfront and Argus is independent on that.

**Comment by tihuan** [comment]
Ah I see! So Argus doesn't manage S3/CloudFront provision stuff and we'll continue to use terraform to manage that or soemthing?

**Comment by ebezzi** [comment]
Yes, both S3 and CloudFront will still be managed by Terraform. We'll just have to repoint the origins to the Argus load balancer.

**Comment by tihuan** [comment]
Awesome thank you! So I suppose this ticket will be for doing that work 👌 ?

**Comment by dsadgat** [comment]
@tihuan please connect with @jakeyheath on this ticket, thanks!

**Comment by tihuan** [comment]
Keeping it as P0 since it's required for Argus deployment to work

**Comment by niknak33** [comment]
Nik to Sync with Timmy after PTO, does it need to be worked on before launch?

**Comment by tihuan** [comment]
No need for the launch, since Argus is not a blocker for launch 👌Sorry I didn't move this to the post launch epic!
