### ISSUE TITLE
Only generate deep zoom files in BE when running locally

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-explorer#920]
Context:
1. Currently in the feature branch BE generates deep zoom files unconditionally

DoD:
1. We should only generate the deep zoom files when we're running BE locally and/or in dev mode

**Comment by tihuan** [comment]
@kaloster I'm thinking maybe this is a 2 pointer, but please feel free to update!

**Comment by kaloster** [comment]
this has been taken care of here: https://github.com/chanzuckerberg/single-cell-explorer/pull/929
